### ISSUE TITLE
Setting CRISPY_TEMPLATE_PACK is required in tests, but it's optional in app

### ISSUE THREAD

**Issue by staaas** [django-crispy-forms/django-crispy-forms#181]
When you run tests for the project using crispy forms with

```
$ python manage.py test
```

 you get 11 exceptions like:

```
ERROR: test_field_wrapper_class (crispy_forms.tests.tests.TestLayoutObjects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stas/dev/Envs/bck/lib/python2.6/site-packages/crispy_forms/tests/tests.py", line 1027, in test_field_wrapper_class
    if settings.CRISPY_TEMPLATE_PACK == 'bootstrap':
  File "/home/stas/dev/Envs/bck/lib/python2.6/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK'
```

But CRISPY_TEMPLATE_PACK  in optional in the code with 'bootstrap' as a default value.

By the way, CRISPY_TEMPLATE_PACK's options are hardcoded around the code:

```
$ grep CRISPY_TEMPLATE_PACK -r .
./CHANGELOG.md: * Adding `CRISPY_TEMPLATE_PACK` setting variable to easily switch between different template packs. Default template pack is now bootstrap.
./README.rst:But you can create a template pack for your own CSS framework and submit it. `see the docs`_ for more information. You can easily switch between both using ``CRISPY_TEMPLATE_PACK`` setting variable, setting it to ``bootstrap`` or ``uni_form``.
./docs/install.rst:If your form CSS framework is not supported, you can create a template pack for it and submit a pull request in github. You can easily switch between both using ``CRISPY_TEMPLATE_PACK`` setting variable, setting it to ``bootstrap`` or ``uni_form``.
./crispy_forms/utils.py:TEMPLATE_PACK = getattr(settings, 'CRISPY_TEMPLATE_PACK', 'bootstrap')
./crispy_forms/utils.py:        and render it using default template 'CRISPY_TEMPLATE_PACK/field.html'
./crispy_forms/tests/test_settings_uniform.py:CRISPY_TEMPLATE_PACK = 'uni_form'
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'uni_form':
./crispy_forms/tests/tests.py:        if (settings.CRISPY_TEMPLATE_PACK == 'uni_form'):
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'bootstrap':
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'bootstrap':
./crispy_forms/tests/tests.py:        if (settings.CRISPY_TEMPLATE_PACK == 'uni_form'):
./crispy_forms/tests/tests.py:        current_pack = settings.CRISPY_TEMPLATE_PACK
./crispy_forms/tests/tests.py:        if (settings.CRISPY_TEMPLATE_PACK == 'uni_form'):
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'bootstrap':
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'uni_form':
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'uni_form':
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'bootstrap':
./crispy_forms/tests/tests.py:        if settings.CRISPY_TEMPLATE_PACK == 'uni_form':
./crispy_forms/tests/test_settings_bootstrap.py:CRISPY_TEMPLATE_PACK = 'bootstrap'
./crispy_forms/templatetags/crispy_forms_tags.py:TEMPLATE_PACK = getattr(settings, 'CRISPY_TEMPLATE_PACK', 'bootstrap')
./crispy_forms/templatetags/crispy_forms_filters.py:TEMPLATE_PACK = getattr(settings, 'CRISPY_TEMPLATE_PACK', 'bootstrap')
./crispy_forms/layout.py:TEMPLATE_PACK = getattr(settings, 'CRISPY_TEMPLATE_PACK', 'bootstrap')
```

**Comment by Ahmed-Muse** [comment]
I also got the same problem... any solution?
