### ISSUE TITLE
Can't convert '__proxy__' object to str implicitly

### ISSUE THREAD

**Issue by ralphje** [django-crispy-forms/django-crispy-forms#350]
When using the Bootstrap3 inline form field template using lazily translated field labels in the current dev branch, an error is raised on:

```
{% crispy_field field 'placeholder' field.label %}
```

The error comes down to:

```
File "..../django-crispy-forms/crispy_forms/templatetags/crispy_forms_field.py" in render
  134.                     widget.attrs[attribute_name] += " " + template.Variable(attribute).resolve(context)

Exception Type: TypeError at ...
Exception Value: Can't convert '__proxy__' object to str implicitly
```

This simple `str` call resolves the issue:

```
widget.attrs[attribute_name] += " " + str(template.Variable(attribute).resolve(context))
```

Using Django 1.7c2 on Python 3.4

**Comment by jnns** [comment]
I'm experiencing an error that I think is related to this issue. The stacktrace is as follows:

```
Internal Server Error: /auth/signup/
Traceback (most recent call last):
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 212, in render
    c = self.get_render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 132, in get_render
    actual_form.form_html = helper.render_layout(actual_form, node_context, template_pack=self.template_pack)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/helper.py", line 293, in render_layout
    template_pack=template_pack
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/layout.py", line 138, in render
    return self.get_rendered_fields(form, form_style, context, template_pack, **kwargs)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in get_rendered_fields
    for field in self.fields
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/layout.py", line 102, in <genexpr>
    for field in self.fields
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/utils.py", line 157, in render_field
    html = template.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 212, in render
    return self._render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py", line 134, in render
    widget.attrs[attribute_name] += " " + template.Variable(attribute).resolve(context)
TypeError: cannot concatenate 'str' and '__proxy__' objects
```

Unfortunately, I encounter this error only on my production system, not locally, and it doesn't occur after restarting the process so debugging is quite hard. Any ideas?

**Comment by carltongibson** [comment]
Happy to take input on a concrete solution but it's not something we've got the bandwidth to address right now. (We'll reassess if it comes up again in the future.)

**Comment by bayersglassey** [comment]
I'm not very familiar with the internals of Django's lazy objects, but it seems to me like this could be fixed by defining `__radd__` for the values returned by `ugettext_lazy`.

Minimal case of the error:
```
from django.utils.translation import ugettext_lazy as _
lazy_text = _("abc")
lazy_text + "123"  # works fine
"123" + lazy_text  # TypeError: Can't convert '__proxy__' object to str implicitly
```

...So if `lazy_text.__radd__` was defined, I think this bug would be solved.

I did a quick test to make sure defining `__radd__` lets us add to strings:
```
class A:
    def __radd__(self, x):
        return x + " A"
    def __add__(self, x):
        return "A " + x

a = A()
a+"123"  # "A 123"
"123"+a  # "123 A"   ...success!
```

**Comment by carltongibson** [comment]
@bayersglassey Nice example. This might be worth suggesting as a fix on Django.
